server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/websocket
    username: WebSocket
    password: 111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect