server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/amaliy
    username: Amaliy
    password: 111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
logging:
  level:
    root: INFO
    amaliy.java.amaliy1: DEBUG
  file:
    name: logs/audit.log

