server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Umar
    username: Umar
    password: 123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true

  upload:
    server:
      folder: C:/Users/ACER/OneDrive/Документы/upload/

api:
  jsonplaceholder: https://jsonplaceholder.typicode.com

jwt:
  token:
    secret: fuckingbrunnetewithbigtitsinfrontofhermom
    validity: 604800000